spring:
  application:
    name: MediTrack
  datasource:
    url: jdbc:mysql://localhost:3306/meditrack?createDatabaseIfNotExist=true
    username: root
    password:

  jwt:
    secret: pwllf3EqSlENvlPXtOCezdUJi6XAmAtrwO+aPVss+UyovF9Hw/4Rg59j/6gCScZTpchy8tI3F94VVAQtfmpFnw==

  flyway:
    clean-disabled: false
